### ISSUE TITLE
Error : object 'na_interpolation' is not exported by 'namespace:imputeTS'

### ISSUE THREAD

**Issue by Calluna-Vulgaris** [neerajdhanraj/imputeTestbench#12]
Installation of imputeTestbench unsuccessful with the following error:

Error : object 'na_interpolation' is not exported by 'namespace:imputeTS'
ERROR: lazy loading failed for package 'imputeTestbench'
Warning in install.packages :
  installation of package ‘imputeTestbench’ had non-zero exit status

I've tried removing imputeTS and reinstalling prior to installing imputeTestbench, with and without restarting R studio and restarting the computer.
Any ideas?

**Comment by fawda123** [comment]
Can you please provide the output from `sessionInfo()`?

**Comment by Calluna-Vulgaris** [comment]
> sessionInfo() R version 3.4.3 (2017-11-30) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  locale: [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       LC_TIME=English_Australia.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] forcats_0.3.0   stringr_1.2.0   dplyr_0.7.4     purrr_0.2.5     readr_1.1.1     tidyr_0.8.1     tibble_1.4.2    ggplot2_2.2.1   tidyverse_1.2.1 forecast_8.2     loaded via a namespace (and not attached):  [1] zoo_1.8-5         reshape2_1.4.3    haven_1.1.1       lattice_0.20-35   colorspace_1.3-2  yaml_2.1.18       rlang_0.2.1       pillar_1.1.0      foreign_0.8-69    glue_1.2.0        [11] TTR_0.23-3        modelr_0.1.2      readxl_1.1.0      bindrcpp_0.2      bindr_0.1         plyr_1.8.4        quantmod_0.4-12   timeDate_3042.101 munsell_0.4.3     gtable_0.2.0      [21] cellranger_1.1.0  rvest_0.3.2       psych_1.8.4       knitr_1.20        tseries_0.10-42   lmtest_0.9-35     parallel_3.4.3    curl_3.1          broom_0.4.4       xts_0.10-1        [31] Rcpp_0.12.15      scales_0.5.0      jsonlite_1.5      fracdiff_1.4-2    mnormt_1.5-5      hms_0.4.2         stringi_1.1.6     grid_3.4.3        quadprog_1.5-5    cli_1.0.0         [41] tools_3.4.3       magrittr_1.5      lazyeval_0.2.1    crayon_1.3.4      pkgconfig_2.0.1   xml2_1.2.0        lubridate_1.7.4   assertthat_0.2.0  httr_1.3.1        rstudioapi_0.7    [51] R6_2.2.2          nnet_7.3-12       nlme_3.1-131      compiler_3.4.3
--
 
> | >
>

**Comment by fawda123** [comment]
Please load `imputeTestbench` and `imputeTS`, then provide the output from `sessionInfo()`.  Also wouldn't hurt to update your R version <https://cran.r-project.org/bin/windows/base/>

**Comment by Calluna-Vulgaris** [comment]
Problem fixed with update. Thanks.
